#!/bin/sh
### function ###

interrupt() {
  echo -e "\n$1"
  exit 0
}

print_help() {
  echo -e \
  "usage: $NEWGIT [OPTION]\n \
  -h --help:\t\thelp of $NEWGIT\n\n \
  -s --save:\t\tsave the current profile\n \
  -n --new:\t\tadd a new profile\n \
  -l --list:\t\tlist saved profile\n \
  -d --delete:\t\tdelete one profile\n \
  -u --use\t\tuse one profile saved\n\n \
  log:\t\toption based on git log\n \
     -l --list:\tlist commiter profile in project\n \
     -u --use:\t\tuse commiter profile\n\n \
  And all git command (git --help)."
}

print_profile() {
  if [ -z $1 ] && [ -z $2 ]; then
    name=$NAME
    email=$EMAIL
  else
    name=$1
    email=$2
  fi
  echo -e "  -> user.name: \033[36m$name\033[0m"
  echo -e "  -> user.email: \033[36m$email\033[0m"
}

add_profile() {
  newProfile="$1"
  IFS=':' read -a new <<< "$1"
  newName=${new[0]}
  newMail=${new[1]}
  listProfile=$(<$FILE)
  IFS=$'\n'
  for profile in $listProfile
  do
    if [ "$profile" = "$newProfile" ]; then
      echo -e "This profile is already saved"
      exit 0
    fi
  done
  echo -e "$newName:$newMail" >> "$FILE"
}

print_list_profile() {
  id=0
  IFS=";"
  for profil in $1
  do
    id=$(($id + 1))
    IFS=':' read -a p <<< "${profil}"
    if [ "${p[0]}" = "$NAME" ] && [ "${p[1]}" = "$EMAIL" ];then
      echo -e "\033[32m [$id] ${p[0]} <${p[1]}>\033[0m"
    else
      echo -e " [$id] ${p[0]} <${p[1]}>"
    fi
  done
}

select_profile() {
  while [ 1 ]
  do
    read -p "Choice profile: " idC
    if [[ $idC =~ ^[0-9]+$ ]] && [ $idC -ne 0 ] && [ $idC -le $id ]; then
      break
    else
      echo -e "Invalid id"
    fi
  done
  i=$(($idC - 1))
  profiles=($1)
  IFS=':' read -a p <<< "${profiles[$i]}"
  print_profile ${p[0]} ${p[1]}
  read -p "Configure with this profile (yes/no)? " choice
  if [ "$choice" = "yes" ] || [ "$choice" = "y" ]; then
    $GIT config user.name ${p[0]}
    $GIT config user.email ${p[1]}
    echo -e "Profile changed in: "
    print_profile ${p[0]} ${p[1]}
  else
    interrupt "Profile not changed"
  fi
}

### end function ###


GIT="/usr/bin/git"
NEWGIT="git profile"
VERSION="$NEWGIT version 0.2.2"
FILE="$HOME/.gitprofile"

COMMIT_CHECK=$(printenv COMMIT_CHECK)
if [ "$?" -eq 1 ]; then
  COMMIT_CHECK=true
else
  COMMIT_CHECK=false
fi

DIR=$($GIT rev-parse --git-dir 2>/dev/null)
if [ "$?" -eq 0 ]; then
  GITREPO=true
else
  GITREPO=false
fi

HEAD=$($GIT rev-parse HEAD 2>/dev/null)
if [ "$?" -eq 0 ]; then
  GITHEAD=true
else
  GITEAD=false
fi

if [ "$GITREPO" = true ]; then
  if [ "$GITHEAD" = true ]; then
    COMMITER=$($GIT log --all --pretty=format:"%cn:%ce" | sort | uniq | tr '\n' ';' | rev | cut -c 2- | rev)
  fi
  NAME=`$GIT config --get user.name`
  EMAIL=`$GIT config --get user.email`
fi

if [ -e "$FILE" ]; then
  if [ -f "$FILE" ]; then
    SAVEDPROFILE=$(cat "$FILE" | tr '\n' ';' | cut -c 2- | rev | cut -c 2- | rev)
  else
    echo -e "WARNING: $FILE: exists and is not a regular file"
    exit 1
  fi
else
  SAVEDPROFILE=""
fi

if [ -z "$NAME" ]; then
  NAME=$USER
fi
if [ -z "$EMAIL" ]; then
  EMAIL="$USER"@"`hostname`"
fi

case $1 in
  --version | version)
    $GIT --version
    echo -e $VERSION
  ;;
  commit)
    STAGED=$($GIT diff --staged --exit-code)
    if [ "$?" -ne 0 ] && [ "$GITREPO" = true ] && [ "$COMMIT_CHECK" = true ]; then
      trap 'interrupt "No commited"' INT
      echo -e "###\033[31m WARNING \033[0m###"
      echo -e "Your commit profile:"
      print_profile
      confirm="$NAME"
      read -p "Confirm name [ $confirm ]? " choice
      if [ "$choice" = "$confirm" ]; then
        $GIT "$@"
      else
        interrupt "No commited"
      fi
    else
      $GIT "$@"
    fi
  ;;
  profile)
    case $2 in
      -h | --help)
        print_help
      ;;
      log)
        if [ "$GITHEAD" = true ]; then
          case $3 in
            -l | --list)
              print_list_profile "$COMMITER"
            ;;
            -u | --use)
              trap 'interrupt "Profile not changed" ' INT
              print_list_profile "$COMMITER"
              select_profile "$COMMITER"
            ;;
            "")
              print_list_profile "$COMMITER"
            ;;
            *)
              echo -e "$NEWGIT --log: '$3' is not a $NEWGIT --log command. See '$NEWGIT -h'."
            ;;
          esac
        else
          $GIT "log"
        fi
      ;;
      -s | --save)
        if ! [ -e "$FILE" ]; then
          echo -e "" > "$FILE"
        fi
        add_profile "$NAME:$EMAIL"
      ;;
      -n | --new)
        trap 'interrupt "No profile added"' INT
        while [ 1 ]
        do
          read -p "user.name: " newName
          if ! [ -z "$newName" ]; then
            break
          fi
        done
        while [ 1 ]
        do
          read -p "user.email: " newEmail
          if ! [ -z "$newEmail" ]; then
            break
          fi
        done
        if ! [ -e "$FILE" ]; then
          echo -e "" > "$FILE"
        fi
        add_profile "$newName:$newEmail"
      ;;
      -l | --list)
        if [ -z "$SAVEDPROFILE" ]; then
          echo -e "No profile saved"
        else
          print_list_profile "$SAVEDPROFILE"
        fi
      ;;
      -d | --delete)
        trap 'interrupt "No profile deleted"' INT
        if [ -z "$SAVEDPROFILE" ]; then
          echo -e "No profile saved"
        else
          print_list_profile "$SAVEDPROFILE"
          while [ 1 ]
          do
            read -p "profile to delete: " idD
            if [[ $idD =~ ^[0-9]+$ ]] && [ $idD -ne 0 ] && [ $idD -le $id ]; then
              break
            else
              echo -e "Invalid id"
            fi
          done
          i=0
          # reset file
          echo -e "" > "$FILE"
          for profile in $SAVEDPROFILE
          do
            i=$(($i + 1))
            if [ $i -eq $idD ]; then
              echo -e "Delete: $profile"
            else
              add_profile "$profile"
            fi
          done
        fi
      ;;
      -u | --use)
        if [ "$GITREPO" = true ]; then
          trap 'interrupt "Profile not changed" ' INT
          if [ -z "$SAVEDPROFILE" ]; then
            echo -e "No profile saved"
          else
            print_list_profile "$SAVEDPROFILE"
            select_profile "$SAVEDPROFILE"
          fi
        else
          $GIT config user.name ""
        fi
      ;;
      "")
        echo -e "Your profile:"
        print_profile
      ;;
      *)
        echo -e "$NEWGIT: '$2' is not a $NEWGIT command. See '$NEWGIT -h'."
      ;;
    esac
  ;;
  *)
    $GIT "$@"
  ;;
esac

