#!/bin/bash
### function ###

interrupt() {
  echo -e "\n$1"
  exit 0
}

print_help() {
  echo -e \
  "usage: $NEWGIT [OPTION]\n \
  -h --help:\t\thelp of $NEWGIT\n\n \
  -s --save:\t\tsave the current profile\n \
  -n --new:\t\tadd a new profile\n \
  -l --list:\t\tlist saved profile\n \
  -d --delete:\t\tdelete one profile\n\n \
  log:\toption based on git log\n \
    -l --list:\t\tlist commiter profile in project\n \
    -u --use:\t\tuse commiter profile\n\n \
  And all git command (git --help)."
}

print_profile() {
  if [ -z $1 ] && [ -z $2 ]; then
    name=$NAME
    email=$EMAIL
  else
    name=$1
    email=$2
  fi
  echo -e "  -> user.name: \033[36m$name\033[0m"
  echo -e "  -> user.email: \033[36m$email\033[0m"
}

check_file() {
  if [ -e "$FILE" ]; then
    if ! [ -f "$FILE" ]; then
      echo -e "$FILE: is not a valid file"
      exit 1
    fi
  else
    touch -- "$FILE"
  fi
}

add_profile() {
  newProfile="$1"
  IFS=':' read -a new <<< "$1"
  newName=${new[0]}
  newMail=${new[1]}
  listProfile=$(<$FILE)
  for profile in $listProfile
  do
    if [ "$profile" = "$newProfile" ]; then
      echo -e "This profile is already saved"
      exit 0
    fi
  done
  echo -e "$newName:$newMail" >> "$FILE"
}

print_list_profile() {
  id=0
  IFS=";"
  for profil in $1
  do
    id=$(($id + 1))
    IFS=':' read -a p <<< "${profil}"
    if [ "${p[0]}" = "$NAME" ] && [ "${p[1]}" = "$EMAIL" ];then
      echo -e "\033[32m [$id] ${p[0]} <${p[1]}>\033[0m"
    else
      echo -e " [$id] ${p[0]} <${p[1]}>"
    fi
  done
}

### end function ###


GIT="/usr/bin/git"
NEWGIT="git profile"
VERSION="$NEWGIT version 1.0"
FILE="$HOME/.gitprofile"

COMMITER=$($GIT log --all --pretty=format:"%cn:%ce" | sort | uniq | tr '\n' ';' | rev | cut -c 2- | rev)

NAME=`$GIT config --get user.name`
EMAIL=`$GIT config --get user.email`

if [ -z "$NAME" ]; then
  NAME=$USER
fi
if [ -z "$EMAIL" ]; then
  EMAIL="$USER"@"`hostname`"
fi

case $1 in
  --version | version)
    $GIT --version
    echo -e $VERSION
  ;;
  commit)
    trap 'interrupt "No commited"' INT
    echo -e "###\033[31m WARNING \033[0m###"
    echo -e "Your commit profile:"
    print_profile
    confirm="$NAME"
    read -p "Confirm name [ $confirm ]? " choice
    if [ "$choice" = "$confirm" ]; then
      $GIT "$@"
    else
      interrupt "No commited"
    fi
  ;;
  profile)
    case $2 in
      -h | --help)
        print_help
      ;;
      log)
        case $3 in
          -l | --list)
            print_list_profile $COMMITER
          ;;
          -u | --use)
            trap 'interrupt "Profile not changed" ' INT
            print_list_profile $COMMITER
            while [ 1 ]
            do
              read -p "Choice profile: " idC
              if [ ! -z $idC ] && [ $idC -ne 0 ] && [ $idC -le $id ]; then
                break
              else
                echo -e "Invalid id"
              fi
            done
            i=$(($idC - 1))
            commiter=($COMMITER)
            IFS=':' read -a user <<< "${commiter[$i]}"
            print_profile ${user[0]} ${user[1]}
            read -p "Configure with this profile (yes/no)? " choice
            if [ "$choice" = "yes" ] || [ "$choice" = "y" ]; then
              $GIT config user.name ${user[0]}
              $GIT config user.email ${user[1]}
              echo -e "Profile changed in: "
              print_profile ${user[0]} ${user[1]}
            else
              interrupt "Profile not changed"
            fi
          ;;
        esac
      ;;
      -s | --save)
        check_file
        add_profile "$NAME:$EMAIL"
      ;;
      -n | --new)
        trap 'interrupt "No profile added"' INT
        check_file
        while [ 1 ]
        do
          read -p "user.name: " newName
          if ! [ -z "$newName" ]; then
            break
          fi
        done
        while [ 1 ]
        do
          read -p "user.email: " newEmail
          if ! [ -z "$newEmail" ]; then
            break
          fi
        done
        add_profile "$newName:$newEmail"
      ;;
      -l | --list)
        if [ -e "$FILE" ]; then
          listProfile=$(cat "$FILE" | tr '\n' ';' | cut -c 2- | rev | cut -c 2- | rev)
        else
          listProfile=""
        fi
        if [ -z "$listProfile" ]; then
          echo -e "No profile saved"
        else
          print_list_profile $listProfile
        fi
      ;;
      -d | --delete)
        trap 'interrupt "No profile deleted"' INT
        if [ -e "$FILE" ]; then
          listProfile=$(cat "$FILE" | tr '\n' ';' | cut -c 2- | rev | cut -c 2- | rev)
        else
          listProfile=""
        fi
        if [ -z "$listProfile" ]; then
          echo -e "No profile saved"
        else
          print_list_profile $listProfile
          while [ 1 ]
          do
            read -p "profile to delete: " idD
            if [ ! -z $idD ] &&  [ $idD -ne 0 ] && [ $idD -le $id ]; then
              break
            else
              echo -e "Invalid id"
            fi
          done
          i=0
          # reset file
          echo -e "" > "$FILE"
          for profile in $listProfile
          do
            i=$(($i + 1))
            if [ $i -eq $idD ]; then
              echo -e "Delete: $profile"
            else
              add_profile $profile
            fi
          done
        fi
      ;;
      "")
        echo -e "Your profile:"
        print_profile
      ;;
      *)
        echo -e "$NEWGIT: '$2' is not a $NEWGIT command. See '$NEWGIT -h'."
      ;;
    esac
  ;;
  *)
    $GIT "$@"
  ;;
esac

